language: node_js
node_js:
- "6.5.0"
script:
- "gulp"  
- "gulp test"
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
install:
- "npm install"
- "npm install bower -g"
- "bower install"
- "gem install scss_lint"